"""
rick_mcp — Rick MCP Server

Package init. Re-exports everything for backward compatibility.
"""

from rick_mcp.constants import (
    CALLSIGN,
    CERTIFICATIONS,
    LANGUAGES,
    MISSION_PHASES,
    PRIMARY_TOOLS,
    SPECIALIZATIONS,
    ResponseFormat,
)
from rick_mcp.formatting import _fmt, _read_md, _safe_tool, _sanitize
from rick_mcp.logging_config import logger
from rick_mcp.models import (
    AttackChainInput,
    CheatsheetInput,
    CompatInput,
    CoverInput,
    CVEInput,
    DebriefInput,
    HardenInput,
    HealthInput,
    MentorInput,
    ModeInput,
    OnboardInput,
    PivotInput,
    ProposalInput,
    ReconInput,
    ReportInput,
    ROEInput,
    ThreatModelInput,
    ToolRecInput,
    TrackerInput,
    VulnInput,
)
from rick_mcp.resources import (
    res_achievements,
    res_changelog,
    res_contributing,
    res_craftsmanship,
    res_entertainment,
    res_heritage,
    res_human,
    res_mantras,
    res_methodology,
    res_profile,
    res_resume_contact,
    res_resume_evidence,
    res_resume_overview,
    res_resume_portfolio,
    res_rick_and_jiveturkey,
    res_security,
    res_soul,
    res_stack,
    res_summary,
    res_the_book,
    res_values,
    res_wwm,
)
from rick_mcp.server import STARTUP_BANNER, mcp
from rick_mcp.tools import (
    rick_attack_chain,
    rick_cheatsheet,
    rick_client_onboarding,
    rick_compatibility_check,
    rick_cover_letter,
    rick_cve,
    rick_debrief,
    rick_demo,
    rick_engagement_proposal,
    rick_hardening,
    rick_health,
    rick_mentorship,
    rick_mode,
    rick_pivot_plan,
    rick_recon,
    rick_report_template,
    rick_roe,
    rick_status,
    rick_threat_model,
    rick_tool_recommend,
    rick_tracker,
    rick_vuln_assess,
)

__all__ = [
    # Constants
    "CALLSIGN",
    "CERTIFICATIONS",
    "LANGUAGES",
    "MISSION_PHASES",
    "PRIMARY_TOOLS",
    "SPECIALIZATIONS",
    "ResponseFormat",
    # Formatting
    "_fmt",
    "_read_md",
    "_safe_tool",
    "_sanitize",
    "logger",
    # Models
    "AttackChainInput",
    "CheatsheetInput",
    "CompatInput",
    "CoverInput",
    "CVEInput",
    "DebriefInput",
    "HardenInput",
    "HealthInput",
    "MentorInput",
    "ModeInput",
    "OnboardInput",
    "PivotInput",
    "ProposalInput",
    "ReconInput",
    "ReportInput",
    "ROEInput",
    "ThreatModelInput",
    "ToolRecInput",
    "TrackerInput",
    "VulnInput",
    # Server
    "mcp",
    "STARTUP_BANNER",
    # Resources
    "res_achievements",
    "res_changelog",
    "res_contributing",
    "res_craftsmanship",
    "res_entertainment",
    "res_heritage",
    "res_human",
    "res_mantras",
    "res_methodology",
    "res_profile",
    "res_resume_contact",
    "res_resume_evidence",
    "res_resume_overview",
    "res_resume_portfolio",
    "res_rick_and_jiveturkey",
    "res_security",
    "res_soul",
    "res_stack",
    "res_summary",
    "res_the_book",
    "res_values",
    "res_wwm",
    # Tools
    "rick_attack_chain",
    "rick_cheatsheet",
    "rick_client_onboarding",
    "rick_compatibility_check",
    "rick_cover_letter",
    "rick_cve",
    "rick_debrief",
    "rick_demo",
    "rick_engagement_proposal",
    "rick_hardening",
    "rick_health",
    "rick_mentorship",
    "rick_mode",
    "rick_pivot_plan",
    "rick_recon",
    "rick_report_template",
    "rick_roe",
    "rick_status",
    "rick_threat_model",
    "rick_tool_recommend",
    "rick_tracker",
    "rick_vuln_assess",
]
